export const protocolResourcesByPhase = {
  1: [
    {
      id: "p1_t1",
      title: "Checklist de Desapegos Quânticos",
      description: "Lista prática para identificar hábitos, pensamentos, vínculos e padrões energéticos a serem liberados no início da jornada.",
      phase: 1,
      icon: "ClipboardList",
    },
    {
      id: "p1_t2",
      title: "Ritual de Queima Consciente com Intenção Biofotônica",
      description: "Técnica escrita + áudio guia para soltar emoções cristalizadas, ativando a liberação celular e vibracional.",
      phase: 1,
      icon: "Wind",
    },
    {
      id: "p1_t3",
      title: "Playlist Frequencial para Liberação Emocional",
      description: "Sequência musical com frequências 396Hz, 417Hz e sons bioativos que auxiliam na liberação do campo emocional.",
      phase: 1,
      icon: "Music",
    },
  ],
  2: [
    {
      id: "p2_t1",
      title: "Roteiro de Banho de Renovação Energética",
      description: "Passo a passo com óleos, ervas e respiração consciente para regenerar o campo vital e alinhar a energia.",
      phase: 2,
      icon: "Leaf",
    },
    {
      id: "p2_t2",
      title: "Diário de Regeneração e Vitalidade",
      description: "Ferramenta de acompanhamento diário com espaço para percepções físicas, emocionais e insights energéticos.",
      phase: 2,
      icon: "BookOpen",
    },
    {
      id: "p2_t3",
      title: "Exercício de Ativação dos Centros Biofotônicos (PDF + Vídeo)",
      description: "Técnica de toque e respiração nos principais pontos bioenergéticos do corpo para estimular a vitalidade.",
      phase: 2,
      icon: "Zap",
    },
  ],
  3: [
    {
      id: "p3_t1",
      title: "Mapa de Ritmo Quântico Pessoal",
      description: "Guia para identificar os melhores horários e ritmos internos de alimentação, descanso e produtividade energética.",
      phase: 3,
      icon: "Sun",
    },
    {
      id: "p3_t2",
      title: "Sequência de Respiração Triádica com Mudras",
      description: "Prática que une respiração, gestos de poder (mudras) e mentalização para restaurar o centro interno.",
      phase: 3,
      icon: "Wind",
    },
    {
      id: "p3_t3",
      title: "Guia de Plantas e Elixires para Equilíbrio Energético",
      description: "Ebook com sugestões de chás, florais e águas solarizadas que favorecem o equilíbrio durante essa fase.",
      phase: 3,
      icon: "Leaf",
    },
  ],
  4: [
    {
      id: "p4_t1",
      title: "Mapa de Ativação dos Chakras Superiores",
      description: "Gráfico com instruções para uso de sons, cores e visualização para abrir e expandir os chakras superiores.",
      phase: 4,
      icon: "Palette",
    },
    {
      id: "p4_t2",
      title: "Prática de Conexão com o Eu Futuro",
      description: "Meditação escrita e gravada para acessar orientações do Eu Quântico e alinhar-se com o propósito expandido.",
      phase: 4,
      icon: "GitBranch",
    },
    {
      id: "p4_t3",
      title: "Guia dos Sonhos Lúcidos e Visões Intuitivas",
      description: "Ferramenta para registrar e interpretar insights durante essa fase de maior abertura da percepção sutil.",
      phase: 4,
      icon: "BookOpen",
    },
  ],
  5: [
    {
      id: "p5_t1",
      title: "Técnica de Reconexão com Linhagens de Luz",
      description: "Roteiro de prática vibracional para restaurar conexões com ancestrais de sabedoria, guias e mentores cósmicos.",
      phase: 5,
      icon: "GitBranch",
    },
    {
      id: "p5_t2",
      title: "Geometria Quântica de Alinhamento (download + explicação)",
      description: "Arquétipo geométrico ativador para imprimir ou visualizar, com função de ajuste vibracional e reorganização do campo.",
      phase: 5,
      icon: "Gem",
    },
    {
      id: "p5_t3",
      title: "Sons de Ressonância Harmônica para Realinhamento",
      description: "Áudio com frequências 528Hz + fractais sonoros que auxiliam o corpo energético na reorganização dimensional.",
      phase: 5,
      icon: "Music",
    },
  ],
  6: [
    {
      id: "p6_t1",
      title: "Cerimônia de Integração e Autocelebração",
      description: "Sugestão de ritual simbólico pessoal ou coletivo para selar a jornada e honrar a transformação.",
      phase: 6,
      icon: "Star",
    },
    {
      id: "p6_t2",
      title: "Mandala de Síntese Pessoal",
      description: "Ferramenta para desenhar, montar ou colorir que representa a união dos aprendizados e vibrações integradas.",
      phase: 6,
      icon: "Palette",
    },
    {
      id: "p6_t3",
      title: "Carta ao Novo Eu (Template para download)",
      description: "Exercício de escrita quântica em que o participante reconhece sua nova versão e projeta sua caminhada a partir do agora.",
      phase: 6,
      icon: "Feather",
    },
  ],
};